import type { ChatLabels } from './types'

export const defaultLabels: Required<ChatLabels> = {
  send: '发送',
  inputPlaceholder: '输入消息... (Enter 发送, Shift+Enter 换行)',
  stop: '中断',
  attachment: '附件',
  addAttachment: '添加附件',
  roleUser: '用户',
  roleAi: 'AI',
  thinking: '思考中...',
  think: '思考过程',
  toolCalls: '工具调用 ({count})',
  toolResult: '结果',
  noHistory: '暂无消息',
  dateToday: '今天',
  dateYesterday: '昨天',
  queued: '排队中',
  loading: '加载中...',
  download: '下载',
  close: '关闭',
  switchServer: '切换服务器',
  connected: '已连接',
  disconnected: '未连接',
  connectFailed: '无法连接到 sbot 服务器',
  retryConnect: '重试',
  selectServer: '选择服务器',
  localServer: '本机 (Local)',
  localServerDesc: '自动检测本地 sbot',
  addRemoteServer: '添加远端服务器',
  namePlaceholder: '名称 (可选)',
  save: '保存',
  cancel: '取消',
  add: '添加',
  sessionList: '会话列表',
  settings: '设置',
  selectSession: '选择会话',
  noSession: '请先选择或创建会话',
  newSession: '新建会话',
  untitledSession: '新会话',
  createSession: '创建会话',
  confirmDeleteSession: '确定删除会话 "{name}"?',
  sessionDeleted: '会话已删除',
  emptySession: '暂无会话',
  createSessionHint: '点击上方新建',
  editSessionNameHint: '双击编辑名称',
  sessionSearchPlaceholder: '搜索会话…',
  sessionNoMatch: '没有匹配的会话',
  agent: 'Agent',
  storage: '存储',
  workpath: '工作目录',
  workpathPlaceholder: '选择工作目录',
  note: '笔记',
  memory: '记忆',
  wiki: 'Wiki',
  autoApproveAll: '自动审批',
  requestApproval: '请求批准',
  autoApproved: '自动审批',
  useChannelDefault: '使用渠道默认值',
  view: '查看',
  usageLast: 'Last',
  usageTotal: 'Total',
  usageCache: 'Cache',
  usageCacheCreation: '写入',
  usageSaved: '节省',
  refresh: '刷新',
  clearHistory: '清除历史',
  confirmClearHistory: '确定清除所有历史记录?',
  historyCleared: '历史记录已清除',
  selectPlaceholder: '请选择…',
  create: '创建',
  executeTool: '执行工具: ',
  allow: '允许',
  alwaysAllowArgs: '始终允许(参数)',
  alwaysAllowAll: '始终允许(工具)',
  deny: '拒绝',
  askSubmit: '提交',
  askOther: '其他',
  askOtherPlaceholder: '输入自定义内容',
  selectDirTitle: '选择目录',
  myComputer: '我的电脑',
  upDir: '↑ 上级目录',
  newFolder: '新建文件夹',
  newFolderPlaceholder: '文件夹名称',
  selectThis: '选择此目录',
  noSubdirs: '没有子目录',
  noSaver: '未配置存储，无法发送',
  selectOrCreate: '← 请选择或创建会话',
  archivedTag: '已归档',
  showArchived: '显示已归档',
  commandTag: '命令',
  exceptionTag: '异常',
  explorerNoRoot: '未设置目录',
  explorerPickRootHint: '请先选择工作目录',
  explorerEmptyDir: '空目录',
  explorerSelectFile: '请选择左侧文件',
  explorerBinaryFile: '二进制文件，无法预览',
  explorerTooLarge: '文件过大 ({size})，无法预览',
  explorerDownload: '下载完整文件',
  explorerToggle: '资源管理器',
  rightPanelToggle: '侧边面板',
  terminal: '终端',
  terminalShell: 'Shell',
  terminalNoShell: '未检测到可用 Shell',
  terminalReconnect: '重新连接',
  explorerFiles: '文件',
  explorerGit: 'Git',
  explorerGitBranch: '当前分支',
  explorerGitNoChanges: '没有 Git 变更',
  explorerGitSelectFile: '请选择左侧变更文件',
  explorerGitNoDiff: '没有可显示的文件变化',
  explorerUnifiedDiff: '单栏',
  explorerSplitDiff: '双栏',
  explorerBaseVersion: '基础版本',
  explorerLocalVersion: '本地修改',
  explorerFullDiff: '完整内容',
  explorerCopyPath: '复制路径',
  explorerCopyDiff: '复制 Diff',
  explorerCopied: '已复制',
  explorerEdit: '编辑',
  explorerEditSave: '保存',
  explorerEditCancel: '取消',
  explorerEditDirty: '未保存',
  explorerEditDiscardConfirm: '当前文件有未保存修改，确定要丢弃？',
  explorerEditStaleConfirm: '文件已被外部修改，是否重新加载并丢弃当前编辑？',
  explorerNewFolder: '新建文件夹',
  explorerNewSubfolder: '新建子文件夹',
  explorerNewFolderPlaceholder: '文件夹名称',
  explorerUpload: '上传文件',
  explorerUploadHere: '上传到此目录',
  explorerUploadProgress: '上传中 {current}/{total}：{name}',
  explorerUploadConflictTitle: '文件已存在',
  explorerUploadConflictSingle: '目标目录已存在同名文件：{name}',
  explorerUploadConflictMultiple: '发现 {count} 个同名文件',
  explorerUploadConflictMore: '还有 {count} 个文件未显示',
  explorerUploadOverwrite: '覆盖',
  explorerUploadSkip: '跳过',
  explorerUploadCancel: '取消上传',
  explorerUploadSummary: '上传 {uploaded} 个，跳过 {skipped} 个，失败 {failed} 个',
  explorerUploadSkippedDirectories: '目录同名已跳过：{names}',
  explorerDelete: '删除',
  explorerConfirmDelete: '确定删除 "{name}"？该操作不可撤销。',
  explorerOperationFailed: '操作失败：{message}',
}

export function resolveLabels(partial?: ChatLabels): Required<ChatLabels> {
  if (!partial) return defaultLabels
  return { ...defaultLabels, ...partial }
}

export function tpl(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? ''))
}
