import type { ChatLabels } from './types'

export const defaultLabels: Required<ChatLabels> = {
  send: '发送',
  inputPlaceholder: '输入消息... (Enter 发送, Shift+Enter 换行)',
  stop: '中断',
  attachment: '附件',
  addAttachment: '添加附件',
  roleUser: '用户',
  roleAi: 'AI',
  thinking: '思考中...',
  think: '思考过程',
  toolCalls: '工具调用 ({count})',
  toolResult: '结果',
  noHistory: '暂无消息',
  dateToday: '今天',
  dateYesterday: '昨天',
  queued: '排队中',
  loading: '加载中...',
  download: '下载',
  close: '关闭',
  switchServer: '切换服务器',
  connected: '已连接',
  disconnected: '未连接',
  connectFailed: '无法连接到 sbot 服务器',
  retryConnect: '重试',
  selectServer: '选择服务器',
  localServer: '本机 (Local)',
  localServerDesc: '自动检测本地 sbot',
  addRemoteServer: '添加远端服务器',
  namePlaceholder: '名称 (可选)',
  save: '保存',
  cancel: '取消',
  add: '添加',
  selectSession: '选择会话',
  noSession: '请先选择或创建会话',
  newSession: '新建会话',
  createSession: '创建会话',
  confirmDeleteSession: '确定删除会话 "{name}"?',
  sessionDeleted: '会话已删除',
  emptySession: '暂无会话',
  createSessionHint: '点击上方新建',
  editSessionNameHint: '双击编辑名称',
  agent: 'Agent',
  storage: '存储',
  workpath: '工作目录',
  workpathPlaceholder: '选择工作目录',
  memory: '记忆',
  wiki: 'Wiki',
  autoApproveAll: '自动审批',
  view: '查看',
  usageLast: 'Last',
  usageTotal: 'Total',
  usageCache: 'Cache',
  refresh: '刷新',
  clearHistory: '清除历史',
  confirmClearHistory: '确定清除所有历史记录?',
  historyCleared: '历史记录已清除',
  selectPlaceholder: '请选择…',
  create: '创建',
  executeTool: '执行工具: ',
  allow: '允许',
  alwaysAllowArgs: '始终允许(参数)',
  alwaysAllowAll: '始终允许(工具)',
  deny: '拒绝',
  askSubmit: '提交',
  askOther: '其他',
  askOtherPlaceholder: '输入自定义内容',
  selectDirTitle: '选择目录',
  myComputer: '我的电脑',
  upDir: '↑ 上级目录',
  newFolder: '新建文件夹',
  newFolderPlaceholder: '文件夹名称',
  selectThis: '选择此目录',
  noSubdirs: '没有子目录',
  noSaver: '未配置存储，无法发送',
  selectOrCreate: '← 请选择或创建会话',
}

export function resolveLabels(partial?: ChatLabels): Required<ChatLabels> {
  if (!partial) return defaultLabels
  return { ...defaultLabels, ...partial }
}

export function tpl(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? ''))
}
